name:                arffparser
version:             0.1.0.0
github:              "arvindd/arffparser"
license:             MIT
author:              "Arvind Devarajan"
maintainer:          "1006084+arvindd@users.noreply.github.com"
copyright:           "Copyright (c) 2019 Arvind Devarajan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/arvindd/arffparser#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - attoparsec
  - word8
  - bytestring

executables:
  arffparser:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arffparser
    - attoparsec
    - bytestring

tests:
  arffparser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arffparser
