name: analyze
version: 0.2.0
synopsis: Haskell data analysis and manipulation library
description: Please see README.md
homepage: https://github.com/DataHaskell/dh-core/analyze
license: BSD3
license-file: LICENSE.md
author: Eric Conlon <ejconlon@gmail.com>, Nikita Tchayka <nikitatchayka@gmail.com>
maintainer: nikitatchayka@gmail.com
copyright: 2017 Analyze contributors
category: Data Science
dependencies:
    - base >= 4.9 && < 5
    - aeson
    - binary
    - bytestring
    - cassava
    - exceptions
    - foldl
    - free
    - hashable
    - lucid
    - text
    - unordered-containers
    - vector

default-extensions: OverloadedStrings

library:
    source-dirs: src
    other-modules: Paths_analyze

tests:
    spec:
        main: Spec.hs
        source-dirs:
            - test
            - src
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - QuickCheck
            - tasty
            - tasty-hunit
            - tasty-quickcheck


